<template>
<table border="0">
  <thead>
    <tr>
      <th>项目管理计划</th>
      <th colspan="2">项目文件</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>范围管理计划</td>
      <td>活动属性</td>
      <td>项目团队派工单</td>
    </tr>
    <tr>
      <td>需求管理计划</td>
      <td>活动清单</td>
      <td>质量控制测量结果</td>
    </tr>
    <tr>
      <td>进度管理计划</td>
      <td>假设日志</td>
      <td>质量测量指标</td>
    </tr>
    <tr>
      <td>成本管理计划</td>
      <td>估算依据</td>
      <td>质量报告</td>
    </tr>
    <tr>
      <td>质量管理计划</td>
      <td>变更日志</td>
      <td>需求文件</td>
    </tr>
    <tr>
      <td>资源管理计划</td>
      <td>成本估算</td>
      <td>需求跟踪矩阵</td>
    </tr>
    <tr>
      <td>沟通管理计划</td>
      <td>持续时间估算</td>
      <td>资源分解结构</td>
    </tr>
    <tr>
      <td>风险管理计划</td>
      <td>问题日志</td>
      <td>资源日历</td>
    </tr>
    <tr>
      <td>采购管理计划</td>
      <td>经验教训登记册</td>
      <td>资源需求</td>
    </tr>
    <tr>
      <td>干系人参与计划</td>
      <td>里程碑清单</td>
      <td>风险登记册</td>
    </tr>
    <tr>
      <td>变更管理计划</td>
      <td>物质资源分配单</td>
      <td>风险报告</td>
    </tr>
    <tr>
      <td>配置管理计划</td>
      <td>项目日历</td>
      <td>进度数据</td>
    </tr>
    <tr>
      <td>范围基准</td>
      <td>项目沟通记录</td>
      <td>进度预测</td>
    </tr>
    <tr>
      <td>进度基准</td>
      <td>项目进度计划</td>
      <td>干系人登记册</td>
    </tr>
    <tr>
      <td>成本基准</td>
      <td>项目进度网络图</td>
      <td>团队章程</td>
    </tr>
    <tr>
      <td>绩效测量基准</td>
      <td>项目范围说明书</td>
      <td>测试与评估文件</td>
    </tr>
    <tr>
      <td>项目生命周期描述</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>开发方法</td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>
</template>
